### ISSUE TITLE
gst/gst.h: No such file or directory error when i try to make gst-nvinfer

### ISSUE THREAD

**Issue by ahmedmuzammilAI** [zhouyuchong/gst-nvinfer-custom#11]
Failed to open '/usr/lib/x86_64-linux-gnu/pkgconfig/opencv4.pc': No such file or directory
No package '/usr/lib/x86_64-linux-gnu/pkgconfig/opencv4.pc' found
Failed to open '/usr/lib/x86_64-linux-gnu/pkgconfig/opencv4.pc': No such file or directory
No package '/usr/lib/x86_64-linux-gnu/pkgconfig/opencv4.pc' found
g++ -c -o gstnvinfer.o -fPIC -std=c++11 -DDS_VERSION=\"6.4\" -I /usr/local/cuda-12.2/include -I /opt/nvidia/deepstream/deepstream-6.4/sources/includes -I /opt/nvidia/deepstream/deepstream-6.4/sources/gst-plugins/gst-nvdspreprocess/include -I /opt/nvidia/deepstream/deepstream-6.4/sources/libs/nvdsinfer -DNDEBUG  gstnvinfer.cpp
In file included from gstnvinfer.cpp:25:
/opt/nvidia/deepstream/deepstream-6.4/sources/includes/gst-nvevent.h:36:10: fatal error: gst/gst.h: No such file or directory
   36 | #include <gst/gst.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:50: gstnvinfer.o] Error 1

i get this error when i try to make gst-nvinfer, although i've set the cuda version and deepstream version correct.
the other two plugins nvdsinfer folder and nvdsinfer_customparser both ran "make" command without any errors.

**Comment by zhouyuchong** [comment]
@ahmedmuzammilAI please install `opencv` and `gstreamer` first
