### ISSUE TITLE
error: 'netwidth' was not declared in this scope

### ISSUE THREAD

**Issue by qustions** [zhouyuchong/gst-nvinfer-custom#2]
@zhouyuchong  please commit this 
To solve this need to change the var `netwidth` to `NETWIDTH` and `netheight` to `NETHEIGHT`
```
gstnvinfer.cpp: In function 'bool tensor_postprocess(NvDsObjectMeta*)':
gstnvinfer.cpp:1648:42: error: 'netwidth' was not declared in this scope
 1648 |     nms_and_adapt(temp, res, NMS_THRESH, netwidth, netheight);
      |                                          ^~~~~~~~
gstnvinfer.cpp:1648:52: error: 'netheight' was not declared in this scope
 1648 |     nms_and_adapt(temp, res, NMS_THRESH, netwidth, netheight);
      |                                                    ^~~~~~~~~

```

**Comment by zhouyuchong** [comment]
@qustions that's a small mistake. try it now :-)

**Comment by qustions** [comment]
Ya its working even in makefile [this line](https://github.com/zhouyuchong/gst-nvinfer-custom/blob/main/Makefile#L27) to `-I ../../gst-plugins/gst-nvdspreprocess/include/` maybe you have different path but default deepstream has this path

**Comment by zhouyuchong** [comment]
@qustions that's a new plugin in deepstream 6.1. though it's useless to be honest.....
