### ISSUE TITLE
How is the Alignment done

### ISSUE THREAD

**Issue by xxiMiaxx** [zhouyuchong/gst-nvinfer-custom#3]
Dear @zhouyuchong, I truly appreciate the amazing work you're putting into these two repositories,

I have successfully managed to run this [repo](https://github.com/zhouyuchong/face-recognition-deepstream) . 

And I followed the steps in the [readme](https://github.com/zhouyuchong/gst-nvinfer-custom) to activate the alignment. 

However when i looked at the results in folders ```origin``` and ```aligned```  it doesn't seem like it's doing alignment, rather it looks like its getting a better smaller crop of the face (face detection).

- Can you please explain how the alignment is done, or point me the the script where the alignment happens?
- is there a different place where i can find alignment results or is it only at ```aligned```?

**Comment by zhouyuchong** [comment]
@xxiMiaxx Have you changed the default ```gst-nvinfer``` to [custom gst-nvinfer](https://github.com/zhouyuchong/gst-nvinfer-custom)? 
+ just check the codes in link above. the alignment is done in ```gst-nvinfer```.
+ you can modify codes to save somewhere else.
