### ISSUE TITLE
How is complied with c++

### ISSUE THREAD

**Issue by NaifOAlharbi** [zhouyuchong/gst-nvinfer-custom#4]
Hello, how can I use this custom with deepstream_infer_meta_test.cpp??
Which part should I change in order to apply it?

**Comment by zhouyuchong** [comment]
@NaifOAlharbi hi, where can i find **deepstream_infer_meta_test.cpp**. 

**custom gst-nvinfer** is used to replace **gst-nvinfer**. you can find original **gst-nvinfer** so file at 
```
/opt/nvidia/deepstream/deepstream-6.1/lib/gst-plugins/libnvdsgst_infer.so
```

**Comment by NaifOAlharbi** [comment]
it is in /`opt/nvidia/deepstream/deepstream-6.1/sources/apps/sample_apps/deepstream-infer-tensor-meta-test`

I compiled the custom` gst-nvinfer `by removing the old  `libnvdsgst_infer.so `in lib and I install the new one. It's working but it doesn't show any alignment  or not saving the cropped face. It shows the bbox but not saved and not aligned. My Retinaface model has the 3 layers for the output, bbox , confidence and landmarks. Is the model that you are using has the landmarks as well? becuase some of Retinaface models give only the bbox and the confidence...

**Comment by zhouyuchong** [comment]
@NaifOAlharbi If u want to save the pics, u can run these commands before run urown script.
```
mkdir -p images/{origin, aligned}
```
u can modify codes [here](https://github.com/zhouyuchong/gst-nvinfer-custom/blob/bc6f9330d6f0864110d3f97db1474fe0534a1e09/gstnvinfer.cpp#L1440) and this [line](https://github.com/zhouyuchong/gst-nvinfer-custom/blob/bc6f9330d6f0864110d3f97db1474fe0534a1e09/gstnvinfer.cpp#L1488).

as for the output of retinaface, I'm using the [tensorrtx](https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface) version, which has only one layer output but also contains landmarks. if u want to use urown model, u should modify these [codes](https://github.com/zhouyuchong/gst-nvinfer-custom/blob/bc6f9330d6f0864110d3f97db1474fe0534a1e09/tensor_extractor.cpp#L45) which extracts info from `usermeta-data`.

**Comment by NaifOAlharbi** [comment]
Thanks for your answer, but is the aligned faces are generated after the Pgie? So the aligned faces will be applied to Sgie which is Aracface right?

**Comment by zhouyuchong** [comment]
@NaifOAlharbi yes that's right. I copy the data from gpu and do alignment. then cover data in gpu with aligned result so sgie will use these data to infer.
