### ISSUE TITLE
[Question] Share CMakeList.txt File? (Error at "make")

### ISSUE THREAD

**Issue by cloudlakecho** [zhouyuchong/gst-nvinfer-custom#5]
Thanks for sharing your codes. 

Would you share your "CMakeList.txt" file? 

Here are details: 
&nbsp;&nbsp; While I try to run "make" command (step 2 in instruction),  I could generate all compiled files except "face_tensor_extractor".

&nbsp;&nbsp; It looks like that I am facing dependent library problem. The log (from make command) is too long, so it is hard to find error.

&nbsp;&nbsp; This is my command line for the "make":
&nbsp;&nbsp; `$ LDFLAGS+="-L/usr/lib" CFLAGS+="-I/usr/include/gstreamer-1.0 -I/usr/include/opencv4 -I/opt/nvidia/deepstream/deepstream-6.1/sources/includes -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/opt/nvidia/deepstream/deepstream-6.1/sources/gst-plugins/gst-nvdspreprocess/include" make >&log`

&nbsp;&nbsp; My target hardware is Nvidia development board (AArch64 not x86_64), so there is additional modification (it looks like your "Makefile" generated in x86_64). 

&nbsp;&nbsp; Thanks.

&nbsp;&nbsp; Run time environment:
&nbsp;&nbsp;&nbsp;&nbsp; OS: Ubuntu 20.04
&nbsp;&nbsp;&nbsp;&nbsp; HW: Nvidia AGX Orin (AArch64)
&nbsp;&nbsp;&nbsp;&nbsp; OpenCV: libopencv 4.5.4 (and libopencv-core4.2:arm64 4.2.0 - this is odd)

**Comment by zhouyuchong** [comment]
Hi, the file `face_tensor_extractor` is no longer in use so u can delete it or pull newer codes. However, there is a littler difference between them so it's up to you.
I'm using x86_64 platform so I'm sorry can't help you with `CMakeList.txt`. This repo is built on top of official gst-nvinfer codes so if you needed maybe you can ask their tech support on forum. :smile:

**Comment by cloudlakecho** [comment]
@zhouyuchong Thanks for the information. I will exclude "face_tensor_extractor" code.

I will try installation without the code.

Yes, I am aware your development environment. The reason of requesting your "CMakeLists.txt" is that I could modify the file (for my environment) and run it (to make "Makefile" for my environment). The "Makefile" file...I couldn't modify.
