### ISSUE TITLE
Is the original image preserved?

### ISSUE THREAD

**Issue by tienluongngoc** [zhouyuchong/gst-nvinfer-custom#6]
Hi @zhouyuchong, thanks for nice project. But I wonder, Is the original image preserved?
Thank you so much!

**Comment by zhouyuchong** [comment]
@tienluongngoc Nope, but you can find them [here](https://github.com/zhouyuchong/gst-nvinfer-custom/blob/83cb0e0a2992d4857e6a3fabb896491b61499c76/gstnvinfer.cpp#L2043). The `cropped` is detection and `whole_frame` is the original frame. Both are `cv::Mat` format so you can simply save them using `cv::imwrite`.
