### ISSUE TITLE
pipeline can‘t stop automatically

### ISSUE THREAD

**Issue by u5e5t** [zhouyuchong/gst-nvinfer-custom#7]
Hi, @zhouyuchong, I have a question for you.
Does the program automatically stop when you set output-tensor-meta=1? I modified it with reference to your previous project, but when using local video as input, the program will run until fps=0, and then it will freeze, and will not stop automatically due to eos. Can you give me some advice?
Thank you so much.

**Comment by zhouyuchong** [comment]
@u5e5t  I think there is no connection between `output-tensor-meta` property and the stop signal of pipeline. If the pipeline freeszes, mostly there are some bugs in codes. 

EOS signal can be handled by modifying codes in `bus callback`.  But again, I don't think the gst-property of nvinfer is the reason.

**Comment by u5e5t** [comment]
@zhouyuchong Thanks for your response, I have solved the problem. The original reason for this problem is that the BS of my second detector is less than or equal to the BS of my primary detector. When I add the BS of the second detector, the program becomes normal. The detailed description about this problem and solutions in https://forums.developer.nvidia.com/t/pipeline-freeze-on-infer-with-output-tensor-meta-enabled-no-error-m essage-or-traceback/209330
