### ISSUE TITLE
Does it work in Jetson?

### ISSUE THREAD

**Issue by willosonico** [zhouyuchong/gst-nvinfer-custom#8]
Does it work in Jetson or it's only x86 code for GPU? Thank you

**Comment by zhouyuchong** [comment]
@willosonico doesn't mater whether jetson or dgpu as long as opencv is installed on your device. 😸

**Comment by willosonico** [comment]
are you sure? because this cudaMemcpy returns 1 (the one in align_preprocess function) 

cudaMemcpy((void *)src_data,
                       (void *)surface->surfaceList[frameIndex].dataPtr,
                       surface->surfaceList[frameIndex].dataSize,
                       cudaMemcpyDeviceToHost)

cudaErrorInvalidValue = 1
This indicates that one or more of the parameters passed to the API call is not within an acceptable range of values.

it actually works in x86

**Comment by zhouyuchong** [comment]
@willosonico yes you are right. It doesn't work on jetson device yet. I'll find some time to fix this.

**Comment by jahdkaran** [comment]
> are you sure? because this cudaMemcpy returns 1 (the one in align_preprocess function) 
> 
> cudaMemcpy((void *)src_data,
>                        (void *)surface->surfaceList[frameIndex].dataPtr,
>                        surface->surfaceList[frameIndex].dataSize,
>                        cudaMemcpyDeviceToHost)
> 
> cudaErrorInvalidValue = 1
> This indicates that one or more of the parameters passed to the API call is not within an acceptable range of values.
> 
> it actually works in x86

Hello,
Could you find a way to solve this issue?

**Comment by zhouyuchong** [comment]
@jahdkaran I've fixed the compile issue, you can find it under [this](https://github.com/zhouyuchong/gst-nvinfer-custom/tree/jetson_nano_cuda10.2) branch. But I didn't test the results since been busy :smiling_face_with_tear: 

Just make sure the path of opencv in jetson is right.
