### ISSUE TITLE
想要请教

### ISSUE THREAD

**Issue by Gakkifan1314** [zhouyuchong/gst-nvinfer-custom#9]
您好，有个问题想要请教一下:
1.关于nvinfer，我看您是修改了gstnvinfer.cpp达到了自定义插件，请问这个插件是一定得在nvinfer的时候使用吗？如果我想在流水线中将仿射变换的图像作为图像的输入，我该如何在deepstream的流水线中串起来，是不是需要自定义预处理的操作？因为nvinfer插件的预处理是内置的，不想用的话可能需要preprocess插件？
期待您的答疑

**Comment by Gakkifan1314** [comment]
您好我想追加一条问题，您的这个修改gstinfer.cpp的目的是不是在模型输出的时候deepstream中probe回调函数中对模型输出进行后处理再做仿射变换也可以达到同样的效果？（虽然没有您这个方便）

**Comment by zhouyuchong** [comment]
@Gakkifan1314 ds新版本的preprocess是将原本的nvinfer的部分代码抽离出来的，其实是一样的，要实现仿射变换仍然需要修改preprocess的源码，因为官方只提供简单的图像预处理功能。回调函数有几点，第一它是阻塞式的，第二回调函数会造成额外的开销，涉及到多次的显存内存io操作，当然理论仍可行。

**Comment by Gakkifan1314** [comment]
好的，感谢您之前的回答。我想继续请问一下，在ds的官方示例中’deepstream-infer-tensor-meta-test‘他是实现了自定义的模型后处理解析接口，然后在pgie_pad_buffer_probe回调函数中进行的处理。是不是说如果是自定义的模型解析只能以这样的方式去进行？而且如您之前说的回调函数会造成额外的开销，如果有很多的模型都需要自定义模型解析的话，是不是其实DS这样的推理框架就不推荐了。
突然想到的，是不是如您一样可以在nvinfer中添加自己的数据格式去输出，修改源码，这样子就避免的上一段中的自定义解析输出在回调函数中执行了？

**Comment by zhouyuchong** [comment]
@Gakkifan1314 如果是后处理的话，模型配置文件中的*custom-lib-path*是可以实现自定义模型后处理的(cpp)。gst的回调函数能实现的功能都可以通过插件实现，gst官方对probe探针的定义决定它并不适合处理复杂的逻辑，真正要实现工程上的功能还是需要对应的gst插件。

**Comment by Gakkifan1314** [comment]
@zhouyuchong 感谢，对于您的回答我有一个疑惑的地方。因为我之前是按照deepstream-infer-tensor-meta-test的示例去自定义了一段模型的后处理函数，然后在probe中进行回调，如官方示例一样。但如果我需要的模型输出结果的结构体在deepstream中nvdsinfer.h中是没有的（现在我就碰到了这样的问题）,所以我的操作是自己定义了一个结构体，然后在probe函数中进行模型的后处理去获得我模型的检测结果，但这样的问题是，这个输出应该并没有办法在ds中传到下一个组件（因为ds应该并不认识这个结构体）。我想问是否有更好的办法。

**Comment by zhouyuchong** [comment]
@Gakkifan1314 两种方法
1.自己定义一个结构体，但是相应的要修改上下游相关的文件，如果你的代码是cpp的话相对比较好操作，python要修改的东西更多。
2.参考官方的user_meta[示例](https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/tree/master/apps/deepstream-custom-binding-test)，将相关的数据加到user_meta中可以在下游获取

**Comment by Gakkifan1314** [comment]
十分感谢您的建议，我会去试试的！
